version: 2
jobs:
  build:
    docker:
      - image: jjanzic/docker-python3-opencv

    steps:
      - checkout

      - run:
          name: Install sudo
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'

      - run:
          name: Install gcc
          command: 'apt-get update && apt-get install -y gcc g++'

      - run:
          name: Install CMAKE
          command: 'apt-get update && sudo apt-get install -y cmake'

      - run:
          name: Install Eigen3
          command: 'apt -y install libeigen3-dev'

      - run:
            name: Current Dir
            command: 'pwd'

      - run:
          name:
          command: 'cd ./build'

      - run:
            name: Current Dir
            command: 'pwd'

      - run:
          name: Creating Build Files
          command: 'cmake .'

      - run:
          name: UKF Unit Testing
          command: './bin/ukftest'
