version: 2
jobs:
  build:
    docker:
      - image: jjanzic/docker-python3-opencv:contrib-opencv-3.4.1

    steps:
      - checkout
      - run:
          command: 'apt-get update && apt-get upgrade -y'

      - run:
          name: Install sudo
          command: 'apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'

      - run:
          name: Install gcc
          command: 'apt-get install -y gcc g++'

      - run:
          name: Install CMAKE
          command: 'sudo apt-get install -y cmake'

      - run:
          name: Install Eigen3
          command: 'apt -y install libeigen3-dev'

      - run:
          name: Creating Build Files
          command: 'cd ./build && cmake .. && make'

      - run:
          name: UKF Unit Testing
          command: './build/bin/ukftest --gtest_filter=-UKFTest.*Simulation*'
