version: 2
jobs:
  build:
    docker:
      - image: debian:stretch

    steps:
      - checkout

      - run:
          name: Install sudo
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'

      - run:
          name: Install gcc
          command: 'apt-get update && apt-get install -y gcc g++'

      - run:
          name: Install CMAKE
          command: 'apt-get update && sudo apt-get install -y cmake'

      - run:
          name:
          command: 'cd ./build'

      - run:
          name: Creating Build Files
          command: 'cd .. && cmake'

      - run:
          name: UKF Unit Testing
          command: './bin/ukftest'
